<?php

/**
 * Basemwb_publishedObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $publishedobject_id
 * @property integer $object
 * @property integer $user
 * @property mwb_object $mwb_object
 * @property mwb_user $mwb_user
 * 
 * @method integer             getPublishedobjectId()  Returns the current record's "publishedobject_id" value
 * @method integer             getObject()             Returns the current record's "object" value
 * @method integer             getUser()               Returns the current record's "user" value
 * @method mwb_object          getMwbObject()          Returns the current record's "mwb_object" value
 * @method mwb_user            getMwbUser()            Returns the current record's "mwb_user" value
 * @method mwb_publishedObject setPublishedobjectId()  Sets the current record's "publishedobject_id" value
 * @method mwb_publishedObject setObject()             Sets the current record's "object" value
 * @method mwb_publishedObject setUser()               Sets the current record's "user" value
 * @method mwb_publishedObject setMwbObject()          Sets the current record's "mwb_object" value
 * @method mwb_publishedObject setMwbUser()            Sets the current record's "mwb_user" value
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_publishedObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_published_object');
        $this->hasColumn('publishedobject_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('object', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('objectindex', array(
             'fields' => 
             array(
              0 => 'object',
             ),
             ));
        $this->index('userindex', array(
             'fields' => 
             array(
              0 => 'user',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mwb_object', array(
             'local' => 'object',
             'foreign' => 'object_id',
             'onDelete' => 'cascade'));

        $this->hasOne('mwb_user', array(
             'local' => 'user',
             'foreign' => 'user_id',
             'onDelete' => 'cascade'));
    }
}