<?php

/**
 * Basemwb_admin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $generated_at
 * @property timestamp $updated_at
 * @property integer $admin_id
 * @property string $firstname
 * @property string $lastname
 * @property string $email
 * @property string $username
 * @property string $password
 * @property string $picturepath
 * @property boolean $superadmin
 * @property Doctrine_Collection $mwb_news_admin
 * 
 * @method timestamp           getGeneratedAt()    Returns the current record's "generated_at" value
 * @method timestamp           getUpdatedAt()      Returns the current record's "updated_at" value
 * @method integer             getAdminId()        Returns the current record's "admin_id" value
 * @method string              getFirstname()      Returns the current record's "firstname" value
 * @method string              getLastname()       Returns the current record's "lastname" value
 * @method string              getEmail()          Returns the current record's "email" value
 * @method string              getUsername()       Returns the current record's "username" value
 * @method string              getPassword()       Returns the current record's "password" value
 * @method string              getPicturepath()    Returns the current record's "picturepath" value
 * @method boolean             getSuperadmin()     Returns the current record's "superadmin" value
 * @method Doctrine_Collection getMwbNewsAdmin()   Returns the current record's "mwb_news_admin" collection
 * @method mwb_admin           setGeneratedAt()    Sets the current record's "generated_at" value
 * @method mwb_admin           setUpdatedAt()      Sets the current record's "updated_at" value
 * @method mwb_admin           setAdminId()        Sets the current record's "admin_id" value
 * @method mwb_admin           setFirstname()      Sets the current record's "firstname" value
 * @method mwb_admin           setLastname()       Sets the current record's "lastname" value
 * @method mwb_admin           setEmail()          Sets the current record's "email" value
 * @method mwb_admin           setUsername()       Sets the current record's "username" value
 * @method mwb_admin           setPassword()       Sets the current record's "password" value
 * @method mwb_admin           setPicturepath()    Sets the current record's "picturepath" value
 * @method mwb_admin           setSuperadmin()     Sets the current record's "superadmin" value
 * @method mwb_admin           setMwbNewsAdmin()   Sets the current record's "mwb_news_admin" collection
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_admin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_admin');
        $this->hasColumn('generated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated_at', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('admin_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('firstname', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('lastname', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('username', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('password', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 40,
             ));
        $this->hasColumn('picturepath', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('superadmin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mwb_news as mwb_news_admin', array(
             'local' => 'admin_id',
             'foreign' => 'writer'));
    }
}