<?php

/**
 * Basemwb_genre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $genre_id
 * @property string $name
 * @property Doctrine_Collection $mwb_object_genre
 * 
 * @method integer             getGenreId()          Returns the current record's "genre_id" value
 * @method string              getName()             Returns the current record's "name" value
 * @method Doctrine_Collection getMwbObjectGenre()   Returns the current record's "mwb_object_genre" collection
 * @method mwb_genre           setGenreId()          Sets the current record's "genre_id" value
 * @method mwb_genre           setName()             Sets the current record's "name" value
 * @method mwb_genre           setMwbObjectGenre()   Sets the current record's "mwb_object_genre" collection
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_genre extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_genre');
        $this->hasColumn('genre_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mwb_object as mwb_object_genre', array(
             'local' => 'genre_id',
             'foreign' => 'genre'));
    }
}