<?php

/**
 * Basemwb_ratedObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $ratedObject_id
 * @property integer $book
 * 
 * @method integer         getRatedObjectId()  Returns the current record's "ratedObject_id" value
 * @method integer         getBook()           Returns the current record's "book" value
 * @method mwb_ratedObject setRatedObjectId()  Sets the current record's "ratedObject_id" value
 * @method mwb_ratedObject setBook()           Sets the current record's "book" value
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_ratedObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_rated_object');
        $this->hasColumn('ratedObject_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('book', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}