<?php

/**
 * Basemwb_boughtObject
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $buydobject_id
 * @property integer $user
 * @property integer $object
 * @property mwb_user $mwb_user
 * @property mwb_object $mwb_object
 * 
 * @method integer          getBuydobjectId()  Returns the current record's "buydobject_id" value
 * @method integer          getUser()          Returns the current record's "user" value
 * @method integer          getObject()        Returns the current record's "object" value
 * @method mwb_user         getMwbUser()       Returns the current record's "mwb_user" value
 * @method mwb_object       getMwbObject()     Returns the current record's "mwb_object" value
 * @method mwb_boughtObject setBuydobjectId()  Sets the current record's "buydobject_id" value
 * @method mwb_boughtObject setUser()          Sets the current record's "user" value
 * @method mwb_boughtObject setObject()        Sets the current record's "object" value
 * @method mwb_boughtObject setMwbUser()       Sets the current record's "mwb_user" value
 * @method mwb_boughtObject setMwbObject()     Sets the current record's "mwb_object" value
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_boughtObject extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_bought_object');
        $this->hasColumn('buydobject_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('object', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('userindex', array(
             'fields' => 
             array(
              0 => 'user',
             ),
             ));
        $this->index('objectindex', array(
             'fields' => 
             array(
              0 => 'object',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('mwb_user', array(
             'local' => 'user',
             'foreign' => 'user_id',
             'onDelete' => 'cascade'));

        $this->hasOne('mwb_object', array(
             'local' => 'object',
             'foreign' => 'object_id',
             'onDelete' => 'cascade'));
    }
}