<?php

/**
 * Basemwb_language
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $language_id
 * @property string $shortcut
 * @property string $country
 * @property string $netsuffix
 * @property Doctrine_Collection $mwb_object_language
 * 
 * @method integer             getLanguageId()          Returns the current record's "language_id" value
 * @method string              getShortcut()            Returns the current record's "shortcut" value
 * @method string              getCountry()             Returns the current record's "country" value
 * @method string              getNetsuffix()           Returns the current record's "netsuffix" value
 * @method Doctrine_Collection getMwbObjectLanguage()   Returns the current record's "mwb_object_language" collection
 * @method mwb_language        setLanguageId()          Sets the current record's "language_id" value
 * @method mwb_language        setShortcut()            Sets the current record's "shortcut" value
 * @method mwb_language        setCountry()             Sets the current record's "country" value
 * @method mwb_language        setNetsuffix()           Sets the current record's "netsuffix" value
 * @method mwb_language        setMwbObjectLanguage()   Sets the current record's "mwb_object_language" collection
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basemwb_language extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mwb_language');
        $this->hasColumn('language_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('shortcut', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('country', 'string', 60, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 60,
             ));
        $this->hasColumn('netsuffix', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('mwb_object as mwb_object_language', array(
             'local' => 'language_id',
             'foreign' => 'language'));
    }
}