<?php

/**
 * mwb_ratedObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_ratedObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_ratedObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_ratedObject');
    }
}