<?php

/**
 * mwb_genre
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mywrittenbooks.dev
 * @subpackage model
 * @author     Tobias Simon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class mwb_genre extends Basemwb_genre
{
}
