<?php

/**
 * mwb_publishedObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_publishedObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_publishedObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_publishedObject');
    }
}