<?php

/**
 * mwb_newsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_newsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_newsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_news');
    }
}