<?php

/**
 * mwb_languageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_languageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_languageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_language');
    }
}