<?php

/**
 * mwb_adminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_adminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_adminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_admin');
    }
}