<?php

/**
 * mwb_boughtObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_boughtObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_boughtObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_boughtObject');
    }
}