<?php

/**
 * mwb_userTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_userTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_userTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_user');
    }
}