<?php

/**
 * mwb_genreTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class mwb_genreTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object mwb_genreTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('mwb_genre');
    }
}