<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/11/22 09:56:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mywrittenbooks',
  'username' => 'root',
  'password' => 'Astalavista',
  'name' => 'doctrine',
)),);
